### PR TITLE
Implement "lax" dep checkers.

### LINKED ISSUE #131: Add "lax" dependency checkers
Currently it is not possible to implement some kind of "forced on" dependency since the dependency check fails early in the event that any of the inputs is inactive.

This is the generally desirable behaviour so that dependencies cannot accidentally become visible because of some less-complete dependency on that field passing, so changing the default behaviour is not an option.

Instead we can add a new `addLaxDepCheckers` method that doesn't fail early when a field is inactive.

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #131.

---
This change is [Reviewable](https://reviewable.io/reviews/fusionapp/methanal/132)

### CODE REVIEW

**Review by mithrandi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fusionapp/methanal/132)* status: all files reviewed, 2 unresolved discussions (waiting on @jonathanj)

___
*[methanal/js/Methanal/View.js, line 65 at r1](https://reviewable.io/reviews/fusionapp/methanal/132#-LuT3wW52Fb6eSekDmfi:-LuT3wW52Fb6eSekDmfj:bgtkeza) ([raw file](https://github.com/fusionapp/methanal/blob/d573c5603b6e6b99f085141a3d375979d54aff02/methanal/js/Methanal/View.js#L65)):*
> ```JavaScript
>             var name = self.inputs[j];
>             var value;
>             if (!self.cache.isActive(name)) {
> ```

It's better to use an un-negated conditional and swap the branches.
___
*[methanal/js/Methanal/View.js, line 770 at r1](https://reviewable.io/reviews/fusionapp/methanal/132#-LuT4V2d52Qqh9erx-0P:-LuT4V2d52Qqh9erx-0Q:baeorbv) ([raw file](https://github.com/fusionapp/methanal/blob/d573c5603b6e6b99f085141a3d375979d54aff02/methanal/js/Methanal/View.js#L770)):*
> ```JavaScript
>             var outputNames = checkers[i][1];
>             var fn = checkers[i][2];
>             self.addDepChecker(inputNames, outputNames, fn, true);
> ```

I think `null` would be a more appropriate default.

**Comment by jonathanj** [comment]
___
*[methanal/js/Methanal/View.js, line 65 at r1](https://reviewable.io/reviews/fusionapp/methanal/132#-LuT3wW52Fb6eSekDmfi:-LuTIRck8p0Bo1JX-kUQ:b-paasr) ([raw file](https://github.com/fusionapp/methanal/blob/d573c5603b6e6b99f085141a3d375979d54aff02/methanal/js/Methanal/View.js#L65)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary><blockquote>

It's better to use an un-negated conditional and swap the branches.
</blockquote></details>

Done. I opted to move the "fail early" case to the bottom.

**Comment by jonathanj** [comment]
___
*[methanal/js/Methanal/View.js, line 770 at r1](https://reviewable.io/reviews/fusionapp/methanal/132#-LuT4V2d52Qqh9erx-0P:-LuTIWJc24kFQ-IGReVW:b-896fix) ([raw file](https://github.com/fusionapp/methanal/blob/d573c5603b6e6b99f085141a3d375979d54aff02/methanal/js/Methanal/View.js#L770)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary><blockquote>

I think `null` would be a more appropriate default.
</blockquote></details>

Done.

**Review by mithrandi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fusionapp/methanal/132)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
