### PR TITLE
`ModalDialog` server-side dismissal notification.

### LINKED ISSUE #117: `ModalDialog` server-side closed/dismissed notification API
In some cases it is beneficial to know when the dialog has been dismissed, so the server side might perform some cleanup.

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #117.

---

This change is [Reviewable](https://reviewable.io/reviews/fusionapp/methanal/118)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[methanal/widgets.py, line 638 [r1]](https://reviewable.io:443/reviews/fusionapp/methanal/118#-KEXD_ROLcPkNac8LKkI:-KEXD_ROLcPkNac8LKkJ:623251626) ([raw file](https://github.com/fusionapp/methanal/blob/c0e0fc0993b1c29eb8c3e6c71468963f4faab6e8/methanal/widgets.py#L638)):_
A potential problem here is that if `connectionMade` is never called, `connectionLost` will never be called. Maybe that's not likely to actually come up, since statically rendering a modal dialog is not really a sensible thing to do? I guess a mention in `whenDismissed` might be good enough then.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/methanal/118)_

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/methanal/118)_

**Comment by jonathanj** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[methanal/widgets.py, line 638 [r1]](https://reviewable.io:443/reviews/fusionapp/methanal/118#-KEXD_ROLcPkNac8LKkI:-KEX_wBmQ9WlNtsjSbNu:1971625583) ([raw file](https://github.com/fusionapp/methanal/blob/c0e0fc0993b1c29eb8c3e6c71468963f4faab6e8/methanal/widgets.py#L638)):_
I think it's probably very unlikely to actually happen, documenting the edge case is probably a better choice than writing a bunch of code to handle the probably-never-used case.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/methanal/118)_

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/methanal/118)_

**Pull request merged**
